ALTER TABLE E_EMP ADD MOT_DE_PASSE VARCHAR2(40);


CREATE TABLE "ACHANKIMPONNE"."E_ROLE" (
  "NO"          NUMBER(7,0),
  "EMP_NO" NUMBER(7,0)  NOT NULL,
  "AUTHORITY" VARCHAR(45) NOT NULL,
  CONSTRAINT "PK_E_ROLE" PRIMARY KEY ("NO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "FINDX" ENABLE,
  CONSTRAINT "FK_ROLE_EMP" FOREIGN KEY ("EMP_NO") REFERENCES "ACHANKIMPONNE"."E_EMP" ("NO") ENABLE
);